/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;
import AppPackage.AnimationClass;import Code.Pengguna.Utama;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Kintan Khairunnisa(1402019052)
 * @author Muhammad Rizky Yuhari(1402019075)
 * @author Rangga Pujangga(1402019090)
 * @author Muhamad Rifqi(1402019058)

 */
public class Login extends javax.swing.JFrame {
        AnimationClass gEraks = new AnimationClass();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        slideShow();
        this.setLocationRelativeTo(null);

    }
    private void apa_Kosong(){
        varPass.setText(null);
        varUser.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tampung = new javax.swing.JPanel();
        Kiri = new javax.swing.JPanel();
        iMG1 = new javax.swing.JLabel();
        iMG2 = new javax.swing.JLabel();
        iMG3 = new javax.swing.JLabel();
        Kanan = new javax.swing.JPanel();
        lUser = new javax.swing.JLabel();
        varUser = new javax.swing.JTextField();
        batasUser = new javax.swing.JSeparator();
        lLogin = new javax.swing.JLabel();
        batasPass = new javax.swing.JSeparator();
        varPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        punyaAkun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Tampung.setBackground(new java.awt.Color(255, 255, 255));
        Tampung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Kiri.setBackground(new java.awt.Color(255, 255, 255));
        Kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iMG1.setBackground(new java.awt.Color(255, 255, 255));
        iMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image.jpg"))); // NOI18N
        Kiri.add(iMG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 520));

        iMG2.setBackground(new java.awt.Color(255, 255, 255));
        iMG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0qf9fy4j-500x500.jpg"))); // NOI18N
        iMG2.setMaximumSize(new java.awt.Dimension(500, 500));
        iMG2.setMinimumSize(new java.awt.Dimension(500, 500));
        iMG2.setPreferredSize(new java.awt.Dimension(500, 500));
        Kiri.add(iMG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        iMG3.setBackground(new java.awt.Color(255, 255, 255));
        iMG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone-x-lcd-display-with-touch-screen-500x500.jpg"))); // NOI18N
        iMG3.setMaximumSize(new java.awt.Dimension(500, 500));
        iMG3.setMinimumSize(new java.awt.Dimension(500, 500));
        iMG3.setPreferredSize(new java.awt.Dimension(500, 500));
        Kiri.add(iMG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Tampung.add(Kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        Kanan.setBackground(new java.awt.Color(32, 33, 35));
        Kanan.setForeground(new java.awt.Color(32, 33, 35));
        Kanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lUser.setForeground(new java.awt.Color(57, 95, 172));
        lUser.setText("Username");
        Kanan.add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        varUser.setBackground(new java.awt.Color(32, 33, 35));
        varUser.setForeground(new java.awt.Color(255, 255, 255));
        varUser.setBorder(null);
        varUser.setCaretColor(new java.awt.Color(255, 255, 255));
        varUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                varUserFocusGained(evt);
            }
        });
        Kanan.add(varUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 350, 30));

        batasUser.setForeground(new java.awt.Color(57, 113, 177));
        Kanan.add(batasUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 350, -1));

        lLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lLogin.setForeground(new java.awt.Color(57, 95, 172));
        lLogin.setText("Password");
        Kanan.add(lLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        Kanan.add(batasPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 350, -1));

        varPass.setBackground(new java.awt.Color(32, 33, 35));
        varPass.setForeground(new java.awt.Color(255, 255, 255));
        varPass.setBorder(null);
        varPass.setCaretColor(new java.awt.Color(255, 255, 255));
        varPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                varPassFocusGained(evt);
            }
        });
        Kanan.add(varPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 350, 30));

        btnLogin.setBackground(new java.awt.Color(57, 95, 172));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Sign In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        Kanan.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 350, 60));

        punyaAkun.setForeground(new java.awt.Color(255, 255, 255));
        punyaAkun.setText("Belum punya akun kan,Yuk Register");
        punyaAkun.setContentAreaFilled(false);
        punyaAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        punyaAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punyaAkunActionPerformed(evt);
            }
        });
        Kanan.add(punyaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 240, -1));

        Tampung.add(Kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 500));

        getContentPane().add(Tampung, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varUserFocusGained

    }//GEN-LAST:event_varUserFocusGained

    private void varPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varPassFocusGained

    }//GEN-LAST:event_varPassFocusGained

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        PreparedStatement conF;
        ResultSet result;
        String uName = varUser.getText();
        String uPass = varPass.getText();

        String query = "SELECT * FROM user WHERE username =? AND password =?";
        try {
            conF = Penghubung.configDB().prepareStatement(query);
            conF.setString(1, uName);
            conF.setString(2, uPass);
            result = conF.executeQuery();

            if(result.next()){
                if(result.getString("role").equals("Pengguna")){
                    JOptionPane.showMessageDialog(null, "YEAY, KAMU BERHASIL LOGIN", "Sukses",JOptionPane.INFORMATION_MESSAGE);
                    Utama puntrn = new Utama(result.getString("nama"), result.getString("username"), result.getString("email"), result.getString("no_hp"), result.getString("jeniskelamin"), result.getString("alamat"), result.getString("password"));
                    puntrn.setVisible(true);
                    puntrn.setLocationRelativeTo(null);
                    puntrn.setDefaultCloseOperation(Utama.EXIT_ON_CLOSE);
                this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Soryy Bos Fiture Udmin Masih Proses Uji Coba", "Gagal",JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password salah");
                apa_Kosong();

            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void punyaAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punyaAkunActionPerformed
        Register log = new Register();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(log.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_punyaAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public void slideShow() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                
                int i = 0;            
                try {
                    while(true) { // infinity loop
                        switch(i) {
                            case 0: // gambar 1 akan bergeser ke gambar 2. 1 -> 2.
                                Thread.sleep(5000); // akan berlangsung 5 detik, 5000ms == 5d
                                gEraks.jLabelXLeft(0, -500, 12, 10, iMG1);
                                gEraks.jLabelXLeft(500, 0, 12, 10, iMG2);
                                gEraks.jLabelXLeft(1000, 500, 12, 10, iMG3);
                                i++;
                            case 1:
                                Thread.sleep(5000); // gambar 2 akan bergeser ke gambar 3. 2 -> 3.
                                gEraks.jLabelXLeft(-500, -1000, 12, 10, iMG1); // akan berlangsung 5 detik, 5000ms == 5d
                                gEraks.jLabelXLeft(0, -500, 12, 10, iMG2);
                                gEraks.jLabelXLeft(500, 0, 12, 10, iMG3);
                                i++;
                            case 2: // gambar 2 akan bergeser ke gambar 3. 2 -> 3.
                                Thread.sleep(5000); // akan berlangsung 5 detik, 5000ms == 5d
                                gEraks.jLabelXLeft(-1000, -500, 12, 10, iMG1);
                                gEraks.jLabelXLeft(-500, 0, 12, 10, iMG2);
                                gEraks.jLabelXLeft(0, 500, 12, 10, iMG3);
                                i++;
                            case 3: // gambar 3 akan bergeser kembali ke gambar 2. 3 -> 2.
                                Thread.sleep(5000); // akan berlangsung 5 detik, 5000ms == 5d
                                gEraks.jLabelXRight(-500, 0, 12, 10, iMG1);
                                gEraks.jLabelXRight(0, 500, 12, 10, iMG2);
                                gEraks.jLabelXRight(500, 1000, 12, 10, iMG3);
                                i=0;
                            
                        }
                    }
                }catch(Exception e) {}
            }
        }).start();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kanan;
    private javax.swing.JPanel Kiri;
    private javax.swing.JPanel Tampung;
    private javax.swing.JSeparator batasPass;
    private javax.swing.JSeparator batasUser;
    private javax.swing.JButton btnLogin;
    public static javax.swing.JLabel iMG1;
    public static javax.swing.JLabel iMG2;
    public static javax.swing.JLabel iMG3;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lUser;
    private javax.swing.JButton punyaAkun;
    private javax.swing.JPasswordField varPass;
    private javax.swing.JTextField varUser;
    // End of variables declaration//GEN-END:variables
}
