/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this tampungTlate file, choose Tools | Templates
 * and open the tampungTlate in the editor.
 */
package Code.Pengguna.Fiture;

import Code.Login;
import static Code.Pengguna.Fiture.Order.Alamats;
import Code.Pengguna.Fiture.System.Item;
import Code.Pengguna.Fiture.System.ItemPembelian;
import Code.Pengguna.Utama;
import Code.Penghubung;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Kintan Khairunnisa(1402019052)
 * @author Muhammad Rizky Yuhari(1402019075)
 * @author Rangga Pujangga(1402019090)
 * @author Muhamad Rifqi(1402019058)

 */
public class Order extends javax.swing.JPanel {
    int total = 0;
    private List<String> tampungP = new ArrayList<>();
    private List<Integer> tampungH = new ArrayList<>();
    private List<Integer> tampungJ = new ArrayList<>();
    private List<String> tampungB = new ArrayList<>();
    private List<JLabel> tampungT = new ArrayList<>();

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        Alamats.setVisible(false);
        Orders.setVisible(true); 
        Pembayaran.setVisible(false);
        risetAll();
    }
    public Order(String nama, String username, String email, String noHP, String jenisKelamin, String alamat, String password) {
        initComponents();
        risetAll();
        Alamats.setVisible(false);
        Orders.setVisible(true); 
        Pembayaran.setVisible(false);
        this.nama = nama;
        this.username = username;
        this.email = email;
        this.noHP = noHP;
        this.jenisKelamin = jenisKelamin;
        this.alamat = alamat;
        this.password = password;
        jTipe.removeAllItems();
        tipeIphone();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alno_hpys
     * regenerated by the Form Editor.
     */
    
    public void risetAll() {
       lcdIphone.setSelected(false);
       minusLCD.setVisible(false);
       jumlahLCD.setVisible(false);
       tambahLCD.setVisible(false); 
       
       
       batraiIphone.setSelected(false);
       minusBatrai.setVisible(false);
       jumlahBatrai.setVisible(false);
       tambahBatrai.setVisible(false);
       
       homeFlex.setSelected(false);
       minusFlex.setVisible(false);
       jumlahFlex.setVisible(false);
       TambahFlex.setVisible(false);
       
       flexVolume.setSelected(false);
       minusVolume.setVisible(false);
       jumlahVolume.setVisible(false);
       tambahVolume.setVisible(false);
       
       jasaPasng.setSelected(false);
       jumlahJasa.setVisible(false);
    }
    // mengecek dan menjumlah segala data yang di beli
    private void cekAll(JCheckBox piliHan, JButton kurang, JLabel jumLah, JButton tambah, int harga) {
        NumberFormat number = NumberFormat.getInstance();
        if (piliHan.isSelected()) {
            kurang.setVisible(true);
            jumLah.setVisible(true);
            tambah.setVisible(true);
            jumLah.setText("1");
            total += harga;
            totalHarga.setText("Rp. " + number.format(total));
            this.tampungP.add(piliHan.getText() + " " + (String)jTipe.getSelectedItem());
            this.tampungH.add(harga);
            this.tampungT.add(jumLah);
        } else {
            kurang.setVisible(false);
            jumLah.setVisible(false);
            tambah.setVisible(false);
            total -= harga * Integer.parseInt(jumLah.getText());
            totalHarga.setText("Rp. " + number.format(total));
            jumLah.setText("0");
            this.tampungP.remove(tampungP.indexOf(piliHan.getText()));
            this.tampungH.remove(tampungH.indexOf(harga));
            this.tampungT.remove(tampungT.indexOf(jumLah));
        }
    }
    public void jasaT(JCheckBox piliHan,JLabel jumLah, int harga) {
        NumberFormat number = NumberFormat.getInstance();
        if (piliHan.isSelected()) {
            jumLah.setVisible(true);
            jumLah.setText("1");
            total += harga;
            totalHarga.setText("Rp. " + number.format(total));
            this.tampungP.add(piliHan.getText());
            this.tampungH.add(harga);
            this.tampungT.add(jumLah);
        } else {
            jumLah.setVisible(false);
            total -= harga * Integer.parseInt(jumLah.getText());
            totalHarga.setText("Rp. " + number.format(total));
            jumLah.setText("0");
            this.tampungP.remove(tampungP.indexOf(piliHan.getText()));
            this.tampungH.remove(tampungH.indexOf(harga));
            this.tampungT.remove(tampungT.indexOf(jumLah));
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Orders = new javax.swing.JPanel();
        hargaJasa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jasaPasng = new javax.swing.JCheckBox();
        totalHarga = new javax.swing.JLabel();
        jTipe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jumlahJasa = new javax.swing.JLabel();
        minusLCD = new javax.swing.JButton();
        tambahLCD = new javax.swing.JButton();
        lcdIphone = new javax.swing.JCheckBox();
        hargaLCD = new javax.swing.JLabel();
        jumlahLCD = new javax.swing.JLabel();
        hargaBatrai = new javax.swing.JLabel();
        batraiIphone = new javax.swing.JCheckBox();
        minusBatrai = new javax.swing.JButton();
        jumlahBatrai = new javax.swing.JLabel();
        tambahBatrai = new javax.swing.JButton();
        minusVolume = new javax.swing.JButton();
        flexVolume = new javax.swing.JCheckBox();
        hargaVolume = new javax.swing.JLabel();
        jumlahVolume = new javax.swing.JLabel();
        tambahVolume = new javax.swing.JButton();
        minusFlex = new javax.swing.JButton();
        hargaFlex = new javax.swing.JLabel();
        jumlahFlex = new javax.swing.JLabel();
        TambahFlex = new javax.swing.JButton();
        homeFlex = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        beliLangsung = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pilihinB = new javax.swing.JLabel();
        Alamats = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        varMail = new javax.swing.JTextField();
        varNama = new javax.swing.JTextField();
        varNo = new javax.swing.JTextField();
        prosesPembayaran = new javax.swing.JButton();
        varAntar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        varAlamat = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        Pembayaran = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        totalHarga1 = new javax.swing.JLabel();
        varDAlamat = new javax.swing.JTextArea();
        pembayaran = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailPembelian = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        konfirmasi = new javax.swing.JButton();
        Sukses = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        varData = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        Orders.setBackground(new java.awt.Color(255, 255, 255));
        Orders.setPreferredSize(new java.awt.Dimension(1050, 250));
        Orders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hargaJasa.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        hargaJasa.setText("Rp. 200.000");
        Orders.add(hargaJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("Dashboard/Order");
        Orders.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setAlignmentX(0.9F);
        jSeparator3.setAlignmentY(0.9F);
        Orders.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (2).png"))); // NOI18N
        jLabel1.setText("  Order");
        Orders.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 50));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setAlignmentX(0.9F);
        jSeparator4.setAlignmentY(0.9F);
        Orders.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 420, 10));

        jasaPasng.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jasaPasng.setText("Jasa Home Service");
        jasaPasng.setContentAreaFilled(false);
        jasaPasng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jasaPasngActionPerformed(evt);
            }
        });
        Orders.add(jasaPasng, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 170, 40));

        totalHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalHarga.setText("Rp.0");
        Orders.add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 150, -1));

        jTipe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jTipe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTipeItemStateChanged(evt);
            }
        });
        jTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipeActionPerformed(evt);
            }
        });
        Orders.add(jTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tipe iPhone:");
        Orders.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jumlahJasa.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jumlahJasa.setForeground(new java.awt.Color(255, 255, 255));
        jumlahJasa.setText("1");
        Orders.add(jumlahJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 20, 40));

        minusLCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        minusLCD.setContentAreaFilled(false);
        minusLCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusLCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusLCDActionPerformed(evt);
            }
        });
        Orders.add(minusLCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 30, 40));

        tambahLCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        tambahLCD.setContentAreaFilled(false);
        tambahLCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahLCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahLCDActionPerformed(evt);
            }
        });
        Orders.add(tambahLCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 30, 40));

        lcdIphone.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        lcdIphone.setText("LCD");
        lcdIphone.setContentAreaFilled(false);
        lcdIphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcdIphoneActionPerformed(evt);
            }
        });
        Orders.add(lcdIphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, 40));

        hargaLCD.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Orders.add(hargaLCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 20));

        jumlahLCD.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jumlahLCD.setText("1");
        Orders.add(jumlahLCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 20, 40));

        hargaBatrai.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Orders.add(hargaBatrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 160, 20));

        batraiIphone.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        batraiIphone.setText("Batrai");
        batraiIphone.setContentAreaFilled(false);
        batraiIphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batraiIphoneActionPerformed(evt);
            }
        });
        Orders.add(batraiIphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 140, 40));

        minusBatrai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        minusBatrai.setContentAreaFilled(false);
        minusBatrai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusBatrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBatraiActionPerformed(evt);
            }
        });
        Orders.add(minusBatrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 30, 40));

        jumlahBatrai.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jumlahBatrai.setText("1");
        Orders.add(jumlahBatrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 20, 40));

        tambahBatrai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        tambahBatrai.setContentAreaFilled(false);
        tambahBatrai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahBatrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBatraiActionPerformed(evt);
            }
        });
        Orders.add(tambahBatrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 30, 40));

        minusVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        minusVolume.setContentAreaFilled(false);
        minusVolume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusVolumeActionPerformed(evt);
            }
        });
        Orders.add(minusVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 30, 40));

        flexVolume.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        flexVolume.setText("Buzzer speaker");
        flexVolume.setContentAreaFilled(false);
        flexVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexVolumeActionPerformed(evt);
            }
        });
        Orders.add(flexVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 190, 40));

        hargaVolume.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Orders.add(hargaVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 170, 20));

        jumlahVolume.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jumlahVolume.setText("1");
        Orders.add(jumlahVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 20, 40));

        tambahVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        tambahVolume.setContentAreaFilled(false);
        tambahVolume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahVolumeActionPerformed(evt);
            }
        });
        Orders.add(tambahVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 30, 40));

        minusFlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        minusFlex.setContentAreaFilled(false);
        minusFlex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusFlexActionPerformed(evt);
            }
        });
        Orders.add(minusFlex, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 30, 40));

        hargaFlex.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Orders.add(hargaFlex, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 160, 20));

        jumlahFlex.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jumlahFlex.setText("1");
        Orders.add(jumlahFlex, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 20, 40));

        TambahFlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        TambahFlex.setContentAreaFilled(false);
        TambahFlex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TambahFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahFlexActionPerformed(evt);
            }
        });
        Orders.add(TambahFlex, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 30, 40));

        homeFlex.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        homeFlex.setText("FLEXIBLE ON/OFF");
        homeFlex.setContentAreaFilled(false);
        homeFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeFlexActionPerformed(evt);
            }
        });
        Orders.add(homeFlex, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 170, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tambahan: ");
        Orders.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total:");
        Orders.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        beliLangsung.setText("Beli Langsung");
        beliLangsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliLangsungActionPerformed(evt);
            }
        });
        Orders.add(beliLangsung, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 180, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("SparePart:");
        Orders.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        pilihinB.setForeground(new java.awt.Color(255, 0, 0));
        Orders.add(pilihinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 124, 190, 20));

        add(Orders, "card3");

        Alamats.setBackground(new java.awt.Color(255, 255, 255));
        Alamats.setPreferredSize(new java.awt.Dimension(1050, 250));
        Alamats.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 128, 131));
        jLabel5.setText("Dashboard/Order");
        Alamats.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setAlignmentX(0.9F);
        jSeparator6.setAlignmentY(0.9F);
        Alamats.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (2).png"))); // NOI18N
        jLabel2.setText("Order  - Alamat Pengiriman");
        Alamats.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 420, 50));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setAlignmentX(0.9F);
        jSeparator5.setAlignmentY(0.9F);
        Alamats.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Alamat Lengkap:");
        Alamats.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 158, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("No telepon:");
        Alamats.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Email:");
        Alamats.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Pengantaran Barang:");
        Alamats.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        varMail.setEnabled(false);
        Alamats.add(varMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 310, 30));
        Alamats.add(varNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 310, 30));
        Alamats.add(varNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 310, 30));

        prosesPembayaran.setText("Lanjut Pembayaran");
        prosesPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesPembayaranActionPerformed(evt);
            }
        });
        Alamats.add(prosesPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 210, 40));

        varAntar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kurir", "Ojek Online", "SiKebut iRepair", "Ambil Di Toko" }));
        Alamats.add(varAntar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 310, 30));

        varAlamat.setColumns(20);
        varAlamat.setRows(5);
        jScrollPane1.setViewportView(varAlamat);

        Alamats.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, 80));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nama: ");
        Alamats.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 30));

        add(Alamats, "card4");

        Pembayaran.setBackground(new java.awt.Color(255, 255, 255));
        Pembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 128, 131));
        jLabel14.setText("Dashboard/Order");
        Pembayaran.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setAlignmentX(0.9F);
        jSeparator7.setAlignmentY(0.9F);
        Pembayaran.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1050, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (2).png"))); // NOI18N
        jLabel15.setText("Order  - Detail");
        Pembayaran.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 420, 50));

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setAlignmentX(0.9F);
        jSeparator8.setAlignmentY(0.9F);
        Pembayaran.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 10));

        totalHarga1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pembayaran.add(totalHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 180, 30));

        varDAlamat.setBackground(new java.awt.Color(240, 240, 240));
        varDAlamat.setColumns(20);
        varDAlamat.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        varDAlamat.setForeground(new java.awt.Color(255, 255, 255));
        varDAlamat.setRows(5);
        varDAlamat.setWrapStyleWord(true);
        varDAlamat.setAutoscrolls(false);
        varDAlamat.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        varDAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        varDAlamat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        varDAlamat.setEnabled(false);
        Pembayaran.add(varDAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 320, 70));

        pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembayaran" }));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        Pembayaran.add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 320, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Alamat Pengiriman:");
        Pembayaran.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Pembayaran Via:");
        Pembayaran.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        detailPembelian.setEditable(false);
        detailPembelian.setColumns(20);
        detailPembelian.setLineWrap(true);
        detailPembelian.setRows(5);
        detailPembelian.setMinimumSize(new java.awt.Dimension(4, 24));
        detailPembelian.setName(""); // NOI18N
        jScrollPane3.setViewportView(detailPembelian);

        Pembayaran.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 390, 210));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Detail Pembelian:");
        Pembayaran.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Total:");
        Pembayaran.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, 30));

        konfirmasi.setText("Konfirmasi");
        konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiActionPerformed(evt);
            }
        });
        Pembayaran.add(konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 180, 30));

        add(Pembayaran, "card4");

        Sukses.setBackground(new java.awt.Color(255, 255, 255));
        Sukses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(128, 128, 131));
        jLabel17.setText("Dashboard/Order");
        Sukses.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setAlignmentX(0.9F);
        jSeparator9.setAlignmentY(0.9F);
        Sukses.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1050, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (2).png"))); // NOI18N
        jLabel22.setText("Order  - Pesanan Berhasil");
        Sukses.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 420, 50));

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setAlignmentX(0.9F);
        jSeparator10.setAlignmentY(0.9F);
        Sukses.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Silakan Membayar Melalui Data Dibawah Ini:");
        Sukses.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Pesanan Berhasil !");
        Sukses.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, 30));

        varData.setColumns(20);
        varData.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        varData.setForeground(new java.awt.Color(255, 255, 255));
        varData.setLineWrap(true);
        varData.setRows(5);
        varData.setWrapStyleWord(true);
        varData.setAutoscrolls(false);
        varData.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        varData.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        varData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        varData.setEnabled(false);
        Sukses.add(varData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 500, 80));

        add(Sukses, "card4");
    }// </editor-fold>//GEN-END:initComponents
    // untuk memindahkan data jenis_iphone dari database ke jCombonox
    public void tipeIphone() {
        PreparedStatement conF;
        ResultSet result;
        String query = "SELECT * FROM jenis_iphone ";
        jTipe.addItem("Pilih Tipe Iphone");
        try {
            conF = Penghubung.configDB().prepareStatement(query);
            result = conF.executeQuery();
            while (result.next()) {
                jTipe.addItem(result.getString("Tipe"));
                //jc adalah nama variabel Jcombobox
                //rs.getString(2) adalah kolom nama_dosen yang diambil secara urut dimulai dari satu
            }
        } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tampilkan", "Gangguan",JOptionPane.INFORMATION_MESSAGE);
            //digunakan untuk menampilkan pesan jika terjadi error 
        }
    }
    public void cekJasa(JCheckBox jasaDong) {
        if(jasaDong.isSelected()){
            varAntar.removeAllItems(); //digunakan untuk membersihkan item jcombobox sebelum diisi.
            varAntar.addItem("Pilih Kurir");
            varAntar.addItem("SiKebut iRepair");
        }
    }
    public void updateData() {
        String namas = varNama.getText();
        String alamat = varAlamat.getText();
        String no = varNo.getText();
        if (!varNo.getText().isEmpty() && !varAlamat.getText().isEmpty() && !varNo.getText().isEmpty()) {
            try{
                String sql = "UPDATE user SET nama = " + "'" + namas +
                            "',no_hp = " + "'" + no +
                            "',alamat = " + "'" + alamat +
                            "' WHERE nama =  " + "'" + nama +
                            "' AND username = " + "'" + username + "'";
                java.sql.Connection conn = (Connection)Penghubung.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, "Maaf masih ada yang blm terisi");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Maaf masih ada yang blm terisi!","Check Kembali",JOptionPane.ERROR_MESSAGE);
            //

        }
    }
    private void jTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipeActionPerformed
        // TODO add your handling code here:
        if(jTipe.getSelectedIndex() == 1){
            hargaLCD.setText("Rp. 315.000");
            hargaBatrai.setText("Rp. 219.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 120.000");
               lcd = 315000;
               batrai = 219000;
               power = 200000;
               volume = 120000;
        }else if(jTipe.getSelectedIndex() == 2){
            hargaLCD.setText("Rp. 425.000");
            hargaBatrai.setText("Rp. 125.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 175.000");
               lcd = 425000;
               batrai = 125000;
               power = 200000;
               volume = 175000;  
        }else if(jTipe.getSelectedIndex() == 3){
            hargaLCD.setText("Rp. 595.000");
            hargaBatrai.setText("Rp. 135.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 195.000");
               lcd = 595000;
               batrai = 135000;
               power = 200000;
               volume = 195000;  
        }else if(jTipe.getSelectedIndex() == 4){
            hargaLCD.setText("Rp. 745.000");
            hargaBatrai.setText("Rp. 175.000");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 195.000");
               lcd = 745000;
               batrai = 175000;
               power = 200000;
               volume = 195000;  
        }else if(jTipe.getSelectedIndex() == 5){
            hargaLCD.setText("Rp. 745.000");
            hargaBatrai.setText("Rp. 190.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 240.000");
               lcd = 745000;
               batrai = 190000;
               power = 200000;
               volume = 240000;  
        }else if(jTipe.getSelectedIndex() == 6){
            hargaLCD.setText("Rp. 845.000");
            hargaBatrai.setText("Rp. 185.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 240.000");
               lcd = 845000;
               batrai = 185000;
               power = 200000;
               volume = 240000;  
        }else if(jTipe.getSelectedIndex() == 7){
            hargaLCD.setText("Rp. 2.300.000");
            hargaBatrai.setText("Rp. 220.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 290.000");
               lcd = 2300000;
               batrai = 220000;
               power = 200000;
               volume = 290000;
        }else if(jTipe.getSelectedIndex() == 8){
            hargaLCD.setText("Rp. 1.395.000");
            hargaBatrai.setText("Rp. 325.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 340.000");
               lcd = 1395000;
               batrai = 325000;
               power = 200000;
               volume = 340000;
        }else if(jTipe.getSelectedIndex() == 9){
            hargaLCD.setText("Rp. 2.250.000");
            hargaBatrai.setText("Rp. 375.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 340.000");
               lcd = 2250000;
               batrai = 375000;
               power = 200000;
               volume = 340000;
        }else if(jTipe.getSelectedIndex() == 10){
            hargaLCD.setText("Rp. 3.500.000");
            hargaBatrai.setText("Rp. 445.100");
            hargaFlex.setText("Rp. 200.000");
            hargaVolume.setText("Rp. 340.000");
               lcd = 3500000;
               batrai = 445000;
               power = 200000;
               volume = 340000;
        }else{
            risetAll();
        }

    }//GEN-LAST:event_jTipeActionPerformed

    private void jTipeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTipeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipeItemStateChanged

    private void minusLCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusLCDActionPerformed
        kurangS(jumlahLCD, jumlahLCD.getText(), lcd);
    }//GEN-LAST:event_minusLCDActionPerformed

    private void tambahLCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahLCDActionPerformed
        tamabaH(jumlahLCD, jumlahLCD.getText(), lcd);
    }//GEN-LAST:event_tambahLCDActionPerformed

    private void lcdIphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcdIphoneActionPerformed
        if(jTipe.getSelectedIndex() == 0){
            pilihinB.setText("Silakan Pilih Tipe iPhone terlebih dahulu");
            risetAll();
        }else{
            cekAll(lcdIphone, minusLCD, jumlahLCD, tambahLCD, lcd);           
        }
    
    }//GEN-LAST:event_lcdIphoneActionPerformed

    private void batraiIphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batraiIphoneActionPerformed
        // TODO add your handling code here:
        if(jTipe.getSelectedIndex() == 0){
            pilihinB.setText("Silakan Pilih Tipe iPhone terlebih dahulu");
            risetAll();
        }else{
            cekAll(batraiIphone, minusBatrai, jumlahBatrai, tambahBatrai, batrai); 
        }
    }//GEN-LAST:event_batraiIphoneActionPerformed

    private void minusBatraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBatraiActionPerformed
        // TODO add your handling code here:
        kurangS(jumlahBatrai, jumlahBatrai.getText(), batrai);
    }//GEN-LAST:event_minusBatraiActionPerformed

    private void tambahBatraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBatraiActionPerformed
        // TODO add your handling code here:
        tamabaH(jumlahBatrai, jumlahBatrai.getText(), batrai);
    }//GEN-LAST:event_tambahBatraiActionPerformed

    private void minusVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusVolumeActionPerformed
        // TODO add your handling code here:
        kurangS(jumlahVolume, jumlahVolume.getText(), volume);
    }//GEN-LAST:event_minusVolumeActionPerformed

    private void flexVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexVolumeActionPerformed
        // TODO add your handling code here:
        if(jTipe.getSelectedIndex() == 0){
            pilihinB.setText("Silakan Pilih Tipe iPhone terlebih dahulu");
            risetAll();
        }else{
            cekAll(flexVolume, minusVolume, jumlahVolume, tambahVolume, power);
        }
    }//GEN-LAST:event_flexVolumeActionPerformed

    private void tambahVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahVolumeActionPerformed
        // TODO add your handling code here:
        tamabaH(jumlahVolume, jumlahVolume.getText(), volume);
    }//GEN-LAST:event_tambahVolumeActionPerformed

    private void minusFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusFlexActionPerformed
        // TODO add your handling code here:
        kurangS(jumlahFlex, jumlahFlex.getText(), power);
    }//GEN-LAST:event_minusFlexActionPerformed

    private void TambahFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahFlexActionPerformed
        // TODO add your handling code here:homeFlex
        tamabaH(jumlahFlex, jumlahFlex.getText(), power);
    }//GEN-LAST:event_TambahFlexActionPerformed

    private void homeFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeFlexActionPerformed
        // TODO add your handling code here:
        if(jTipe.getSelectedIndex() == 0){
            pilihinB.setText("Silakan Pilih Tipe iPhone terlebih dahulu");
            risetAll();
        }else{
            cekAll(homeFlex, minusFlex, jumlahFlex, TambahFlex, volume);
        }
    }//GEN-LAST:event_homeFlexActionPerformed

    private void beliLangsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliLangsungActionPerformed
        // TODO add your handling code here:
        if(lcdIphone.isSelected() || batraiIphone.isSelected() || homeFlex.isSelected() || flexVolume.isSelected()){
            cekJasa(jasaPasng);
            for (int i = 0; i < tampungT.size(); i++) {
                this.tampungJ.add(Integer.parseInt(tampungT.get(i).getText()));
            }
//        Alamats alamat = new Alamats(nama, username, email, noHP, jenisKelamin, password, tampungP, tampungH, tampungJ);
            PreparedStatement conF;
            ResultSet result;

            String query = "SELECT * FROM user WHERE username =?";
            try {
                conF = Penghubung.configDB().prepareStatement(query);
                conF.setString(1, username);
                result = conF.executeQuery();

                if(result.next()){
                        varNama.setText(result.getString("nama"));
                        varAlamat.setText(result.getString("alamat"));
                        varNo.setText(result.getString("no_hp"));
                        varMail.setText(result.getString("email"));

                }else{
                    JOptionPane.showMessageDialog(null, "Mengalami masalah pada data server");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            Pembayaran.setVisible(false);
            Alamats.setVisible(true);   
            Orders.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Anda Belum Memutuskan Membeli!!", "Gagal",JOptionPane.INFORMATION_MESSAGE);
        }
                  

    }//GEN-LAST:event_beliLangsungActionPerformed

    private void jasaPasngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jasaPasngActionPerformed
        // TODO add your handling code here:
        if(jTipe.getSelectedIndex() == 0){
            pilihinB.setText("Silakan Pilih Tipe iPhone terlebih dahulu");
            risetAll();
        }else{
            jasaT(jasaPasng, jumlahJasa, 200000);
        }
    }//GEN-LAST:event_jasaPasngActionPerformed

    private void prosesPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesPembayaranActionPerformed
        // TODO add your handling code here
        pembayarans();
        if(varAntar.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null, "Ada data yang blm terisi, silakan di cek kembali", "Gagal",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (!varNama.getText().isEmpty() && !varAlamat.getText().isEmpty() && !varNo.getText().isEmpty()) {
                printAlamat();
                printDetail();
                updateData();
                Pembayaran.setVisible(true);
                Alamats.setVisible(false);   
                Orders.setVisible(false);   
            }else{
                JOptionPane.showMessageDialog(null, "Ada data yang blm terisi, silakan di cek kembali", "Gagal",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_prosesPembayaranActionPerformed

    private void konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiActionPerformed
        // TODO add your handling code here:
        String inNama = varNama.getText();
        String inAlamat = varAlamat.getText();
	String inPesanan= details;
        String inProses = "Sedang Di Proses";
        String inTelp = varNo.getText();        
	String inHarga = ""+totalss;
	String inPembayaran = (String)pembayaran.getSelectedItem();
        if (pembayaran.getSelectedIndex() == 0) {
              JOptionPane.showMessageDialog(null, "Masih ada data yang tidak valid nih, Yuk di cek lagi","Check Kembali",JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                String sql = "INSERT INTO pesannan VALUES (id,'"+inNama+"','"+inTelp+"','"+inAlamat+"','"+inPesanan+"','"+inHarga+"','"+inPembayaran+"','"+username+"','"+inProses+"')";
                java.sql.Connection conn = (Connection)Penghubung.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                updatePay();
                Pembayaran.setVisible(false);
                Alamats.setVisible(false);   
                Sukses.setVisible(true); 
                Orders.setVisible(false); 
                tampungP.clear();
                tampungH.clear();
                tampungJ.clear();
                tampungB.clear();
                tampungT.clear();
                JOptionPane.showMessageDialog(null, "Pesanan Anda berhasil","Silakan Melakukan Pembayaran",JOptionPane.INFORMATION_MESSAGE);

            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, "Bermasalah");
            }
        }
    }//GEN-LAST:event_konfirmasiActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranActionPerformed

    
    public void kurangS(JLabel items, String jumlas, int harga) {
        int temp = Integer.parseInt(jumlas);
        if (temp > 1) {
            NumberFormat number = NumberFormat.getInstance();
            temp--;
            items.setText("" + temp);
            Item barang = new ItemPembelian(items.getText(),temp, harga);
            if(barang instanceof ItemPembelian){
                ItemPembelian items1 = (ItemPembelian)barang;
                items1.setHarga(harga);
                items1.setJumlahItem(temp);
                total -= (items1.getHarga());
            }
            totalHarga.setText("Rp. " + number.format(total));
        }
    }
    public void tamabaH(JLabel items, String jumlas, int harga) {
        int temp = Integer.parseInt(jumlas);
        if (temp < 10) {
            NumberFormat number = NumberFormat.getInstance();
            temp++;
            items.setText("" + temp);
            Item barang = new ItemPembelian(items.getText(),temp, harga);
            if(barang instanceof ItemPembelian){
                ItemPembelian items1 = (ItemPembelian)barang;
                items1.setHarga(harga);
                items1.setJumlahItem(temp);
                 total += (items1.getHarga());
            }
            totalHarga.setText("Rp. " + number.format(total));
        }
    }
    
    public void printAlamat() {
        alamats1 = varNama.getText() + "\n";
        alamats1 += varNo.getText() + "\n";
        alamats1 += varAlamat.getText();
        varDAlamat.setText(alamats1);
    }
    
    public void printDetail() {
        int totals = 0;
        detail = String.format("%5s %5s %5s %10s %10s", "SperePart", "|", "Harga(Rp.)", "|", "Jumlah\n");
        detail += String.format("%s", "-----------------------------------------------------------------\n");
        
        NumberFormat number = NumberFormat.getInstance();
        for (int i = 0; i < tampungH.size(); i++) {
            detail += String.format("%10s %10s %10s %10s %10s\n", tampungP.get(i), "|", tampungH.get(i), "|", tampungJ.get(i));
            details += tampungP.get(i) + "\t" + tampungH.get(i) + "\t" + tampungJ.get(i)+ "\n";
            totals += tampungH.get(i) * tampungJ.get(i);
        }
        detail += String.format("%s", "-----------------------------------------------------------------\n");
        detailPembelian.setText(detail);
        totalss = totals;
        totalHarga1.setText("Rp. " + number.format(totals));
    }    
    
    public void pembayarans() {
        PreparedStatement conF;
        ResultSet result;
        String query = "SELECT * FROM pay";
        try {
            conF = Penghubung.configDB().prepareStatement(query);
            result = conF.executeQuery();
            while (result.next()) {
                pembayaran.addItem(result.getString("payment"));
                tampungB.add(result.getString("no_rek") + " A/N " + result.getString("atas_nama")); 
                //jc adalah nama variabel Jcombobox
                //rs.getString(2) adalah kolom nama_dosen yang diambil secara urut dimulai dari satu
            }
        } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tampilkan", "Gangguan",JOptionPane.INFORMATION_MESSAGE);
            //digunakan untuk menampilkan pesan jika terjadi error 
        }
    }
    public void updatePay() {
        String rek = "";
        rek = (String)pembayaran.getSelectedItem() + "\n";
        if(pembayaran.getSelectedIndex() == 1){
            rek += tampungB.get(0) + "\n";
        }else if(pembayaran.getSelectedIndex() == 2){
            rek += tampungB.get(1) + "\n";
        }else if(pembayaran.getSelectedIndex() == 3){
            rek += tampungB.get(2) + "\n";
        }
        rek+= totalHarga1.getText();
        varData.setText(rek);
        
    }
    private String nama;
    private String username;
    private String email;
    private String noHP;
    private String jenisKelamin;
    private String alamat;
    private String password;
    private String alamats1;
    private int lcd;
    private int batrai;
    private int power;
    private int volume;
    private int tambahan;
    String detail = "";
    String details = "";
    int totalss = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Alamats;
    public static javax.swing.JPanel Orders;
    public static javax.swing.JPanel Pembayaran;
    public static javax.swing.JPanel Sukses;
    private javax.swing.JButton TambahFlex;
    private javax.swing.JCheckBox batraiIphone;
    private javax.swing.JButton beliLangsung;
    private javax.swing.JTextArea detailPembelian;
    private javax.swing.JCheckBox flexVolume;
    private javax.swing.JLabel hargaBatrai;
    private javax.swing.JLabel hargaFlex;
    private javax.swing.JLabel hargaJasa;
    private javax.swing.JLabel hargaLCD;
    private javax.swing.JLabel hargaVolume;
    private javax.swing.JCheckBox homeFlex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> jTipe;
    private javax.swing.JCheckBox jasaPasng;
    private javax.swing.JLabel jumlahBatrai;
    private javax.swing.JLabel jumlahFlex;
    private javax.swing.JLabel jumlahJasa;
    private javax.swing.JLabel jumlahLCD;
    private javax.swing.JLabel jumlahVolume;
    private javax.swing.JButton konfirmasi;
    private javax.swing.JCheckBox lcdIphone;
    private javax.swing.JButton minusBatrai;
    private javax.swing.JButton minusFlex;
    private javax.swing.JButton minusLCD;
    private javax.swing.JButton minusVolume;
    private javax.swing.JComboBox<String> pembayaran;
    private javax.swing.JLabel pilihinB;
    private javax.swing.JButton prosesPembayaran;
    private javax.swing.JButton tambahBatrai;
    private javax.swing.JButton tambahLCD;
    private javax.swing.JButton tambahVolume;
    private javax.swing.JLabel totalHarga;
    private javax.swing.JLabel totalHarga1;
    private javax.swing.JTextArea varAlamat;
    private javax.swing.JComboBox<String> varAntar;
    private javax.swing.JTextArea varDAlamat;
    private javax.swing.JTextArea varData;
    private javax.swing.JTextField varMail;
    private javax.swing.JTextField varNama;
    private javax.swing.JTextField varNo;
    // End of variables declaration//GEN-END:variables

    
}
