/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code.Pengguna.Fiture;

import Code.Login;
import Code.Penghubung;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Kintan Khairunnisa(1402019052)
 * @author Muhammad Rizky Yuhari(1402019075)
 * @author Rangga Pujangga(1402019090)
 * @author Muhamad Rifqi(1402019058)

 */
public class Profile extends javax.swing.JPanel {
        Random rnd = new Random();

    /**
     * Creates new form Profil
     */
    public Profile() {
        initComponents();
    }

    public Profile(String nama, String username, String email, String noHP, String jenisKelamin, String alamat, String password) {
        initComponents();
        this.nama = nama;
        this.username = username;
        this.email = email;
        this.noHP = noHP;
        this.jenisKelamin = jenisKelamin;
        this.alamat = alamat;
        this.password = password;
        varNama.setText(nama);
        varNo.setText(noHP);
        varEmail.setText(email);
        varAlamat.setText(alamat);
        varPass.setText(password);
        jComboBox1.removeAllItems();
        if(jenisKelamin == "Laki - Laki"){
            jComboBox1.addItem(jenisKelamin);
            jComboBox1.addItem("Prempuan");
        }else if(jenisKelamin == "Prempuan"){
            jComboBox1.addItem(jenisKelamin);
            jComboBox1.addItem("Laki - Laki");
        }else{
            jComboBox1.addItem("Pilih Jenis Kelamin");
            jComboBox1.addItem("Laki - Laki");
            jComboBox1.addItem("Prempuan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ErrorPass = new javax.swing.JLabel();
        ErrorNo = new javax.swing.JLabel();
        varEmail = new javax.swing.JTextField();
        varNama = new javax.swing.JTextField();
        varNo = new javax.swing.JTextField();
        prosesEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        varAlamat = new javax.swing.JTextArea();
        ErrorAlamat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        varPass = new javax.swing.JPasswordField();
        Generate = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        ErrorName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setAlignmentX(0.9F);
        jSeparator3.setAlignmentY(0.9F);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-37, 44, 1050, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("Dashboard/Profile");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (2).png"))); // NOI18N
        jLabel1.setText("Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 420, 50));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setAlignmentX(0.9F);
        jSeparator4.setAlignmentY(0.9F);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Alamat Lengkap:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        ErrorPass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 294, 350, 20));

        ErrorNo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 195, 350, 20));

        varEmail.setEditable(false);
        varEmail.setEnabled(false);
        varEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varEmailKeyReleased(evt);
            }
        });
        jPanel1.add(varEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, 30));

        varNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varNamaKeyReleased(evt);
            }
        });
        jPanel1.add(varNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 210, 30));

        varNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varNoKeyReleased(evt);
            }
        });
        jPanel1.add(varNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 210, 30));

        prosesEdit.setText("Edit");
        prosesEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesEditActionPerformed(evt);
            }
        });
        jPanel1.add(prosesEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, 40));

        varAlamat.setColumns(20);
        varAlamat.setRows(5);
        varAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varAlamatKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(varAlamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 210, 120));

        ErrorAlamat.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 225, 350, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("No telepon:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki - Laki", "Perempuan" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Jenis Kelamin:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        varPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varPassActionPerformed(evt);
            }
        });
        varPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varPassKeyReleased(evt);
            }
        });
        jPanel1.add(varPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 210, 30));

        Generate.setText("Generate");
        Generate.setContentAreaFilled(false);
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        jPanel1.add(Generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 100, 30));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view (1).png"))); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, 30));

        ErrorName.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, 350, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void prosesEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesEditActionPerformed
        String namas = varNama.getText();
        String alamat = varAlamat.getText();
        String no = varNo.getText();
        String pass = varPass.getText();
        String jenis = (String)jComboBox1.getSelectedItem();
            if (cekPassword && cekNama && cekNo && cekAlamat) {
                try{
                    String sql = "UPDATE user SET nama = " + "'" + namas +
                                "',no_hp = " + "'" + no +
                                "',jeniskelamin = " + "'" + jenis +
                                "',alamat = " + "'" + alamat +
                                "',password = " + "'" + pass +
                                "' WHERE  email =  " + "'" + email +
                                "' AND username = " + "'" + username + "'";
                    java.sql.Connection conn = (Connection)Penghubung.configDB();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    Login log = new Login();
                    log.dispose();
                    JOptionPane.showMessageDialog(null, "Ah Mantap, Data mu sudah terupdate!","Sukses",JOptionPane.INFORMATION_MESSAGE);
                }catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(this, "Maaf masih ada yang blm terisi");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Maaf masih ada yang blm terisi!","Check Kembali",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_prosesEditActionPerformed

    private void varPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varPassActionPerformed

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
        // TODO add your handling code here:
        int rands = rnd.nextInt(5)+8;
        StringBuilder sb = new StringBuilder(rands);
        for (int i = 1; i <= rands; i++){
            sb.append(RegexPass().charAt(rnd.nextInt(RegexPass().length())));
        }
        varPass.setText(sb.toString());
        StringSelection stringSelection = new StringSelection(varPass.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        String PATTERN = "[a-zA-Z0-9!@#$%&]+";
        if (varPass.getText().isEmpty()) {
            ErrorPass.setText("Password Harus diisi Sob!");
            cekPassword = false;
        } else if (varPass.getText().matches(PATTERN) && !varPass.getText().isEmpty()) {
            if (varPass.getText().length() < 8) {
                ErrorPass.setText("Passowrd terlalu singkat");
                cekPassword = false;
            } else if (varPass.getText().length() > 12) {
                ErrorPass.setText("Passowrd terlalu Panjang");
                cekPassword = false;
            } else {
                ErrorPass.setText("");
                cekPassword = true;
            }
        } else {
            ErrorPass.setText("Password Lu ngga valid Sob");
            cekPassword = false;
        }
    }//GEN-LAST:event_GenerateActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            varPass.setEchoChar((char)0);
        }else{
            varPass.setEchoChar('*');
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void varNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varNamaKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[A-Za-z]+";
        String nama = varNama.getText().replaceAll(" ", "");
        if (nama.isEmpty()) {
            ErrorName.setText("Nama harus diisi!");
            cekNama = false;
        } else if (!nama.matches(PATTERN)) {
            ErrorName.setText("Nama tidak valid");
            cekNama = false;
        } else {
            ErrorName.setText("");
            cekNama = true;
        }
    }//GEN-LAST:event_varNamaKeyReleased

    private void varNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varNoKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]+";
        if (varNo.getText().isEmpty()) {
            ErrorNo.setText("Nomer harus diisi!");
            cekNo = false;
        } else if (!varNo.getText().matches(PATTERN)) {
            ErrorNo.setText("Nomer tidak valid");
            cekNo = false;
        } else {
            ErrorNo.setText("");
            cekNo = true;
        }
    }//GEN-LAST:event_varNoKeyReleased

    private void varPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varPassKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z0-9!@#$%&]+";
        if (varPass.getText().isEmpty()) {
            ErrorPass.setText("Password Harus diisi Sob!");
            cekPassword = false;
        } else if (varPass.getText().matches(PATTERN) && !varPass.getText().isEmpty()) {
            if (varPass.getText().length() < 8) {
                ErrorPass.setText("Passowrd terlalu singkat");
                cekPassword = false;
            } else if (varPass.getText().length() > 12) {
                ErrorPass.setText("Passowrd terlalu Panjang");
                cekPassword = false;
            } else {
                ErrorPass.setText("");
                cekPassword = true;
            }
        } else {
            ErrorPass.setText("Password ngga valid Sob");
            cekPassword = false;
        }
    }//GEN-LAST:event_varPassKeyReleased

    private void varEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_varEmailKeyReleased

    private void varAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varAlamatKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[A-Za-z]+";
        if (varAlamat.getText().isEmpty()) {
            ErrorAlamat.setText("Alamat Harus di isi terlebih dahulu!");
            cekAlamat = false;
        } else {
            ErrorAlamat.setText("");
            cekAlamat = true;
        }
    }//GEN-LAST:event_varAlamatKeyReleased

   private String RegexPass(){
        String number = "0123456789";
        return number;
    }
    private String nama;
    private String username;
    private String email;
    private String noHP;
    private String jenisKelamin;
    private String alamat;
    private String password;
    boolean cekNama = false;
    boolean cekPassword = false;
    boolean cekUsername = false;
    boolean cekAlamat = false;
    boolean cekNo = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorAlamat;
    private javax.swing.JLabel ErrorName;
    private javax.swing.JLabel ErrorNo;
    private javax.swing.JLabel ErrorPass;
    private javax.swing.JButton Generate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton prosesEdit;
    private javax.swing.JTextArea varAlamat;
    private javax.swing.JTextField varEmail;
    private javax.swing.JTextField varNama;
    private javax.swing.JTextField varNo;
    private javax.swing.JPasswordField varPass;
    // End of variables declaration//GEN-END:variables
}
