/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code.Pengguna.Fiture;

import Code.Penghubung;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kintan Khairunnisa(1402019052)
 * @author Muhammad Rizky Yuhari(1402019075)
 * @author Rangga Pujangga(1402019090)
 * @author Muhamad Rifqi(1402019058)

 */
public class Riwayat extends javax.swing.JPanel {
    public DefaultTableModel model;
    
    /**
     * Creates new form Riwayat
     */
    public Riwayat() {
        initComponents();
        cekBOs();

    }

    public Riwayat(String nama, String username, String email, String noHP, String jenisKelamin, String alamat, String password) {
        initComponents();
        this.nama = nama;
        this.username = username;
        this.email = email;
        this.noHP = noHP;
        this.jenisKelamin = jenisKelamin;
        this.alamat = alamat;
        this.password = password;
        cekBOs();
    }
    public void cekBOs(){
        String[] atas =  {"No","Nama", "Nomer Hp", "Alamat", "Pesanan", "Harga", "Pay", "Status"};
        model = new DefaultTableModel(atas,0);
        newDataa.setModel(model);
        PreparedStatement conf;
        ResultSet rs;
        TableColumn column;
        newDataa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = newDataa.getColumnModel().getColumn(0); 
        column.setPreferredWidth(20);
        column = newDataa.getColumnModel().getColumn(1); 
        column.setPreferredWidth(100); 
        column = newDataa.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = newDataa.getColumnModel().getColumn(3); 
        column.setPreferredWidth(100); 
        column = newDataa.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = newDataa.getColumnModel().getColumn(5); 
        column.setPreferredWidth(75); 
        column = newDataa.getColumnModel().getColumn(6); 
        column.setPreferredWidth(75); 
        column = newDataa.getColumnModel().getColumn(7); 
        column.setPreferredWidth(100); 
        String sql= "SELECT * FROM pesannan WHERE id_Pembeli = " + "'" + username + "'";
        
        try {
            java.sql.Connection conn = (Connection)Penghubung.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            rs = pstm.executeQuery();
            int i = 1;
            while(rs.next()){
                String n = rs.getString("nama");
                String t = rs.getString("no");
                String k = rs.getString("alamat");
                String a = rs.getString("pesanan");
                String h = rs.getString("harga");
                String te = rs.getString("pembayaran");
                String tes = rs.getString("status");
                model.addRow(new Object[]{i, n, t, k, a, h, te,tes});
                newDataa.setModel(model);
                i++;
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Maaf Gagal");
            Logger.getLogger(Riwayat.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        newDataa = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setAlignmentX(0.9F);
        jSeparator3.setAlignmentY(0.9F);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-37, 44, 1050, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("Dashboard/Riwayat Order");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart (2).png"))); // NOI18N
        jLabel1.setText("Riwayat Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 420, 50));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setAlignmentX(0.9F);
        jSeparator4.setAlignmentY(0.9F);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 10));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        newDataa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Nama", "Nomer Hp", "Alamat", "Pesanan", "Harga", "Pay", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        newDataa.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(newDataa);
        if (newDataa.getColumnModel().getColumnCount() > 0) {
            newDataa.getColumnModel().getColumn(0).setMinWidth(2);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 780, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));
    }// </editor-fold>//GEN-END:initComponents

    private String nama;
    private String username;
    private String email;
    private String noHP;
    private String jenisKelamin;
    private String alamat;
    private String password;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable newDataa;
    // End of variables declaration//GEN-END:variables
}
